version: '3.9'

services:
  calsync:
    build: .
    container_name: calsync-claude
    restart: unless-stopped
    environment:
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - ICLOUD_USERNAME=${ICLOUD_USERNAME}
      - ICLOUD_PASSWORD=${ICLOUD_PASSWORD}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - DEBUG=${DEBUG:-false}
      - SYNC_CONFIG__SYNC_INTERVAL_MINUTES=${SYNC_INTERVAL_MINUTES:-30}
      - SYNC_CONFIG__MAX_EVENTS_PER_SYNC=${MAX_EVENTS_PER_SYNC:-1000}
      - SYNC_CONFIG__SYNC_PAST_DAYS=${SYNC_PAST_DAYS:-30}
      - SYNC_CONFIG__SYNC_FUTURE_DAYS=${SYNC_FUTURE_DAYS:-365}
    volumes:
      - ./data:/data
      - ./credentials:/credentials
    command: ['daemon']
