# Secure Docker Compose configuration using Docker secrets
services:
  calsync:
    build: .
    container_name: calsync-claude
    restart: unless-stopped
    secrets:
      - google_client_id
      - google_client_secret
      - icloud_username
      - icloud_password
    environment:
      # Use secrets mounted at /run/secrets/
      - GOOGLE_CLIENT_ID_FILE=/run/secrets/google_client_id
      - GOOGLE_CLIENT_SECRET_FILE=/run/secrets/google_client_secret
      - ICLOUD_USERNAME_FILE=/run/secrets/icloud_username
      - ICLOUD_PASSWORD_FILE=/run/secrets/icloud_password
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - DEBUG=${DEBUG:-false}
      - SYNC_CONFIG__SYNC_INTERVAL_MINUTES=${SYNC_INTERVAL_MINUTES:-30}
      - SYNC_CONFIG__MAX_EVENTS_PER_SYNC=${MAX_EVENTS_PER_SYNC:-1000}
      - SYNC_CONFIG__SYNC_PAST_DAYS=${SYNC_PAST_DAYS:-30}
      - SYNC_CONFIG__SYNC_FUTURE_DAYS=${SYNC_FUTURE_DAYS:-365}
    volumes:
      - ./data:/data
      - ./credentials:/credentials
    command: ['daemon']

secrets:
  google_client_id:
    file: ./secrets/google_client_id.txt
  google_client_secret:
    file: ./secrets/google_client_secret.txt
  icloud_username:
    file: ./secrets/icloud_username.txt
  icloud_password:
    file: ./secrets/icloud_password.txt